version: "3.2"
services:
  postgres:
    image: postgres:latest
    container_name: feature-flag-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./data-db:/var/lib/postgresql/data
  postgres-test:
    image: postgres:latest
    container_name: feature-flag-postgres-test
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5430:5432"
    volumes:
      - ./init-test.sql:/docker-entrypoint-initdb.d/init-test.sql
# volumes:
#   db-data:
