version: "3.2"
services:
  postgres:
    image: postgres:latest
    container_name: feature-flag-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-data: