version: "3.2"
services:
  postgres:
    image: postgres:latest
    container_name: feature-flag-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
