name: Pioneer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: build docker compose
        run: docker-compose -f ./docker/docker-compose.yml
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: |
          cd ./server
          npm install

      - run: npm run build --if-present

      - name: Run Tests
        run: |
          cd ./server
          npm test
